spring:
  application:
    name: slillb-ark-discovery

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # N찾o registrar o pr처prio servidor
    fetch-registry: false        # N찾o buscar inst창ncias
